{'author': [{'name': 'washingtontimes',
             'uri': 'http://gdata.youtube.com/feeds/api/users/washingtontimes'}],
 'category': ['http://gdata.youtube.com/schemas/2007#playlist',
              'washington',
              'news',
              'politics'],
 'group': None,
 'items_per_page': '25',
 'link': [{'href': 'http://www.youtube.com/view_play_list?p=3C046B163FA3957C',
           'rel': 'alternate',
           'type': 'text/html'},
          {'href': 'http://gdata.youtube.com/feeds/api/playlists/3C046B163FA3957C',
           'rel': 'http://schemas.google.com/g/2005#feed',
           'type': 'application/atom+xml'},
          {'href': 'http://gdata.youtube.com/feeds/api/playlists/3C046B163FA3957C/batch',
           'rel': 'http://schemas.google.com/g/2005#batch',
           'type': 'application/atom+xml'},
          {'href': 'http://gdata.youtube.com/feeds/api/playlists/3C046B163FA3957C?start-index=1&max-results=25',
           'rel': 'self',
           'type': 'application/atom+xml'}],
 'logo': 'http://www.youtube.com/img/pic_youtubelogo_123x63.gif',
 'playlistId': '3C046B163FA3957C',
 'start_index': '1',
 'subtitle': 'The best of The Washington Times YouTube Channel',
 'title': 'TWT Home',
 'total_results': '15',
 'updated': '2011-04-13T16:37:29.000Z'}



[{'author': [{'name': 'washingtontimes',
              'uri': 'http://gdata.youtube.com/feeds/api/users/washingtontimes'}],
  'category': ['http://gdata.youtube.com/schemas/2007#playlist',
               {'label': 'Entertainment', 'term': 'Entertainment'},
               'evan rachel wood',
               'the conspirator',
               'robert redford',
               'mildred pierce',
               'liz glover',
               'dawne langford',
               'gucci',
               'jill stuart',
               'washington',
               'd.c.',
               "ford's theater"],
  'comments': [{'count_hint': '0',
                'href': 'http://gdata.youtube.com/feeds/api/videos/DLyt64ZtZcw/comments'}],
  'content': 'Liz Glover chats with Evan Rachel Wood at the D.C. Premiere of "The Conspirator."',
  'description': 'Liz Glover chats with Evan Rachel Wood at the D.C. Premiere of "The Conspirator."',
  'link': [{'href': 'http://www.youtube.com/watch?v=DLyt64ZtZcw&feature=youtube_gdata',
            'rel': 'alternate',
            'type': 'text/html'},
           {'href': 'http://gdata.youtube.com/feeds/api/videos/DLyt64ZtZcw/responses',
            'rel': 'http://gdata.youtube.com/schemas/2007#video.responses',
            'type': 'application/atom+xml'},
           {'href': 'http://gdata.youtube.com/feeds/api/videos/DLyt64ZtZcw/related',
            'rel': 'http://gdata.youtube.com/schemas/2007#video.related',
            'type': 'application/atom+xml'},
           {'href': 'http://m.youtube.com/details?v=DLyt64ZtZcw',
            'rel': 'http://gdata.youtube.com/schemas/2007#mobile',
            'type': 'text/html'},
           {'href': 'http://gdata.youtube.com/feeds/api/videos/DLyt64ZtZcw',
            'rel': 'related',
            'type': 'application/atom+xml'},
           {'href': 'http://gdata.youtube.com/feeds/api/playlists/3C046B163FA3957C/DD2E2C946BA4FCC6',
            'rel': 'self',
            'type': 'application/atom+xml'}],
  'media': {'category': [{'label': 'Entertainment',
                          'text': 'Entertainment'}],
            'content': [{'duration': '65',
                         'expression': 'full',
                         'isDefault': 'true',
                         'medium': 'video',
                         'type': 'application/x-shockwave-flash',
                         'url': 'http://www.youtube.com/v/DLyt64ZtZcw?f=playlists&app=youtube_gdata',
                         '{http://gdata.youtube.com/schemas/2007}format': '5'},
                        {'duration': '65',
                         'expression': 'full',
                         'medium': 'video',
                         'type': 'video/3gpp',
                         'url': 'rtsp://v4.cache4.c.youtube.com/CiULENy73wIaHAnMZW2G6628DBMYDSANFEgGUglwbGF5bGlzdHMM/0/0/0/video.3gp',
                         '{http://gdata.youtube.com/schemas/2007}format': '1'},
                        {'duration': '65',
                         'expression': 'full',
                         'medium': 'video',
                         'type': 'video/3gpp',
                         'url': 'rtsp://v4.cache5.c.youtube.com/CiULENy73wIaHAnMZW2G6628DBMYESARFEgGUglwbGF5bGlzdHMM/0/0/0/video.3gp',
                         '{http://gdata.youtube.com/schemas/2007}format': '6'}],
            'description': 'Liz Glover chats with Evan Rachel Wood at the D.C. Premiere of "The Conspirator."',
            'duration': '65',
            'keywords': "evan rachel wood, the conspirator, robert redford, mildred pierce, liz glover, dawne langford, gucci, jill stuart, washington, d.c., ford's theater",
            'player': 'http://www.youtube.com/watch?v=DLyt64ZtZcw&feature=youtube_gdata_player',
            'thumbnail': [{'height': '240',
                           'time': '00:00:32.500',
                           'url': 'http://i.ytimg.com/vi/DLyt64ZtZcw/0.jpg',
                           'width': '320'},
                          {'height': '90',
                           'time': '00:00:16.250',
                           'url': 'http://i.ytimg.com/vi/DLyt64ZtZcw/1.jpg',
                           'width': '120'},
                          {'height': '90',
                           'time': '00:00:32.500',
                           'url': 'http://i.ytimg.com/vi/DLyt64ZtZcw/2.jpg',
                           'width': '120'},
                          {'height': '90',
                           'time': '00:00:48.750',
                           'url': 'http://i.ytimg.com/vi/DLyt64ZtZcw/3.jpg',
                           'width': '120'}],
            'title': 'Evan Rachel Wood at the D.C. Premiere of "The Conspirator"'},
  'position': '1',
  'statistics': {'favorite_count': '0', 'view_count': '151'},
  'title': 'Evan Rachel Wood at the D.C. Premiere of "The Conspirator"',
  'updated': '2011-04-14T15:27:50.536Z'},




